## Feature engineering for Machine Learning - main table

In [1]:
import pandas as pd
main_df = pd.read_csv('/Users/merryxmm7/Documents/GitHub/Final_Project_Ironhack/Premier_league_predictor/main_df.csv')
main_df

,Date,HomeTeam,AwayTeam,gf,ga,FTR_df,HTHG_df,HTAG_df,HTR_df,Referee_df,...,away_Loss,away_Points,away_Position,Position,Matches,Wins,Draws,Losses,Goal_Difference,Points
0,2018-08-11,AFC Bournemouth,Cardiff City,2,0,H,1,0,H,K Friend,...,1,0,17,3,1,1,0,0,2,3
1,2018-08-12,Arsenal FC,Manchester City,0,2,A,0,1,A,M Oliver,...,0,3,5,15,1,0,0,1,-2,0
2,2018-08-11,Fulham FC,Crystal Palace,0,2,A,0,1,A,M Dean,...,1,3,4,18,1,0,0,1,-2,0
3,2018-08-11,Huddersfield Town,Chelsea FC,0,3,A,0,2,A,C Kavanagh,...,0,3,2,19,1,0,0,1,-3,0
4,2018-08-12,Liverpool FC,West Ham United,4,0,H,2,0,H,A Taylor,...,0,0,20,1,1,1,0,0,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2252,2024-05-19,Crystal Palace,Aston Villa,5,0,H,2,0,H,D Bond,...,0,68,4,10,38,13,10,15,-1,49
2253,2024-05-19,Liverpool FC,Wolverhampton Wanderers,2,0,H,2,0,H,C Kavanagh,...,0,46,14,3,38,24,10,4,45,82
2254,2024-05-19,Luton Town,Fulham FC,2,4,A,1,2,A,M Donohue,...,0,47,13,18,38,6,8,24,-33,26
2255,2024-05-19,Manchester City,West Ham United,3,1,H,2,1,H,J Brooks,...,1,52,9,1,38,28,7,3,62,91
2256,2024-05-19,Sheffield United,Tottenham Hotspur,0,3,A,0,1,A,A Madley,...,1,66,5,20,38,3,7,28,-69,16

In [2]:
# Drop specified columns
columns_to_drop = ['FTR_away', 'HTHG_away', 'HTAG_away', 'HTR_away', 'Referee_away', 
                   'HS_away', 'AS_away', 'HST_away', 'AST_away', 'HF_away', 'AF_away', 
                   'HC_away', 'AC_away', 'HY_away', 'AY_away', 'HR_away', 'AR_away', 
                   'B365H_away', 'B365D_away', 'B365A_away', 'time_away', 'day_away', 
                   'venue_away', 'xg', 'xga', 'venue_df', 'time_df']

main_df = main_df.drop(columns=columns_to_drop)

# Rename columns to remove '_df' suffix
main_df.columns = [col.replace('_df', '') for col in main_df.columns]

main_df.columns

Index(['Date', 'HomeTeam', 'AwayTeam', 'gf', 'ga', 'FTR', 'HTHG', 'HTAG',
       'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC',
       'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'season',
       'Matchweek', 'day', 'result', 'poss', 'sh', 'sot', 'dist', 'fk', 'pk',
       'pkatt', 'FTHG', 'FTAG', 'away_result', 'away_gf', 'away_ga', 'away_xg',
       'away_xga', 'away_poss', 'away_sh', 'away_sot', 'away_dist', 'away_fk',
       'away_pk', 'away_pkatt', 'away_Goal_Difference', 'away_Win',
       'away_Draw', 'away_Loss', 'away_Points', 'away_Position', 'Position',
       'Matches', 'Wins', 'Draws', 'Losses', 'Goal_Difference', 'Points'],
      dtype='object')

In [3]:
main_df['avg_goal_difference'] = main_df['Goal_Difference'] / main_df['Matchweek']
main_df['avg_away_goal_difference'] = main_df['away_Goal_Difference'] / main_df['Matchweek']

In [8]:
main_df = main_df.sort_values(by=['HomeTeam', 'Matchweek', 'season'])
main_df.columns

Index(['Date', 'HomeTeam', 'AwayTeam', 'gf', 'ga', 'FTR', 'HTHG', 'HTAG',
       'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC',
       'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'season',
       'Matchweek', 'day', 'result', 'poss', 'sh', 'sot', 'dist', 'fk', 'pk',
       'pkatt', 'FTHG', 'FTAG', 'away_result', 'away_gf', 'away_ga', 'away_xg',
       'away_xga', 'away_poss', 'away_sh', 'away_sot', 'away_dist', 'away_fk',
       'away_pk', 'away_pkatt', 'away_Goal_Difference', 'away_Win',
       'away_Draw', 'away_Loss', 'away_Points', 'away_Position', 'Position',
       'Matches', 'Wins', 'Draws', 'Losses', 'Goal_Difference', 'Points',
       'avg_goal_difference', 'avg_away_goal_difference'],
      dtype='object')

In [5]:
# Step 1: Transform the target variable 'result'
main_df['result'] = main_df['result'].apply(lambda x: 1 if x == 'W' else 0)
main_df['away_result'] = main_df['away_result'].apply(lambda x: 1 if x == 'W' else 0)

# Step 2: Transform the 'HTR' column
main_df['HTR'] = main_df['HTR'].apply(lambda x: 1 if x == 'H' else 0)
main_df['FTR'] = main_df['FTR'].apply(lambda x: 1 if x == 'H' else 0)

In [ ]:
main_df.head()

In [22]:
import pandas as pd

# Define columns to move for home team and away team
columns_to_move_home = ['poss', 'sh', 'sot', 'dist', 'fk', 'pk', 'Goal_Difference',
                        'pkatt', 'FTHG', 'gf', 'ga', 'FTR', 'HTHG', 'HTR', 'HS', 
                        'HST', 'HF', 'HC', 'HY', 'HR']
columns_to_move_away = ['HTAG', 'AS', 'AST', 'AF', 'AC', 'AY', 'AR', 'FTAG', 
                        'away_gf', 'away_ga', 'away_xg', 'away_xga', 'away_poss', 
                        'away_sh', 'away_sot', 'away_dist', 'away_fk', 'away_pk', 
                        'away_pkatt', 'away_Goal_Difference']

# Filter columns from the main DataFrame
home_team_df = main_df[['Date', 'Matchweek'] + columns_to_move_home]
away_team_df = main_df[['Date', 'Matchweek'] + columns_to_move_away]

# Merge home team and away team DataFrames based on the next matchweek
next_matchweek = main_df['Matchweek'] + 1
home_team_next_matchweek = pd.merge(main_df[['Date', 'Matchweek']], 
                                    home_team_df, 
                                    left_on=['Date', next_matchweek], 
                                    right_on=['Date', 'Matchweek'], 
                                    how='left')
away_team_next_matchweek = pd.merge(main_df[['Date', 'Matchweek']], 
                                    away_team_df, 
                                    left_on=['Date', next_matchweek], 
                                    right_on=['Date', 'Matchweek'], 
                                    how='left')

# Fill missing values with 0
home_team_next_matchweek.fillna(0, inplace=True)
away_team_next_matchweek.fillna(0, inplace=True)

# Drop unnecessary columns
home_team_next_matchweek.drop(columns=['Date', 'Matchweek'], inplace=True)
away_team_next_matchweek.drop(columns=['Date', 'Matchweek'], inplace=True)

# Calculate cumulative averages
home_team_cumulative_avg = home_team_next_matchweek.expanding().mean()
away_team_cumulative_avg = away_team_next_matchweek.expanding().mean()

# Reset index
home_team_cumulative_avg.reset_index(drop=True, inplace=True)
away_team_cumulative_avg.reset_index(drop=True, inplace=True)

# Concatenate home team and away team cumulative averages
final_df = pd.concat([home_team_cumulative_avg, away_team_cumulative_avg], axis=1)

# Display the final DataFrame
final_df

,Matchweek_x,Matchweek_y,poss,sh,sot,dist,fk,pk,Goal_Difference,pkatt,FTHG,gf,ga,FTR,HTHG,HTR,HS,HST,HF,HC,HY,HR,Matchweek_x,Matchweek_y,HTAG,AS,AST,AF,AC,AY,AR,FTAG,away_gf,away_ga,away_xg,away_xga,away_poss,away_sh,away_sot,away_dist,away_fk,away_pk,away_pkatt,away_Goal_Difference
0,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000
1,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000
2,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000
3,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000
4,1.400000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1.400000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2252,19.459831,0.025743,0.073236,0.011540,0.003995,0.021749,0.0,0.0,-0.019973,0.0,0.002663,0.002663,0.001775,0.000444,0.000888,0.000444,0.011984,0.004882,0.011540,0.005770,0.001332,0.0,19.459831,0.025743,0.000888,0.014203,0.004439,0.016866,0.006658,0.002219,0.0,0.001775,0.002663,0.000888,0.001154,0.000976,0.059920,0.013759,0.006658,0.023613,0.000444,0.0,0.0,0.001775
2253,19.467613,0.025732,0.073203,0.011535,0.003993,0.021739,0.0,0.0,-0.019965,0.0,0.002662,0.002662,0.001775,0.000444,0.000887,0.000444,0.011979,0.004880,0.011535,0.005768,0.001331,0.0,19.467613,0.025732,0.000887,0.014197,0.004437,0.016859,0.006655,0.002218,0.0,0.001775,0.002662,0.000887,0.001154,0.000976,0.059894,0.013753,0.006655,0.023602,0.000444,0.0,0.0,0.001775
2254,19.475388,0.025721,0.073171,0.011530,0.003991,0.021729,0.0,0.0,-0.019956,0.0,0.002661,0.002661,0.001774,0.000443,0.000887,0.000443,0.011973,0.004878,0.011530,0.005765,0.001330,0.0,19.475388,0.025721,0.000887,0.014191,0.004435,0.016851,0.006652,0.002217,0.0,0.001774,0.002661,0.000887,0.001153,0.000976,0.059867,0.013747,0.006652,0.023592,0.000443,0.0,0.0,0.001774
2255,19.483156,0.025709,0.073138,0.011525,0.003989,0.021720,0.0,0.0,-0.019947,0.0,0.002660,0.002660,0.001773,0.000443,0.000887,0.000443,0.011968,0.004876,0.011525,0.005762,0.001330,0.0,19.483156,0.025709,0.000887,0.014184,0.004433,0.016844,0.006649,0.002216,0.0,0.001773,0.002660,0.000887,0.001152,0.000975,0.059840,0.013741,0.006649,0.023582,0.000443,0.0,0.0,0.001773
2256,19.491360,0.025698,0.073106,0.011520,0.003988,0.021710,0.0,0.0,-0.019938,0.0,0.002658,0.002658,0.001772,0.000443,0.000886,0.000443,0.011963,0.004874,0.011520,0.005760,0.001329,0.0,19.491360,0.025698,0.000886,0.014178,0.004431,0.016837,0.006646,0.002215,0.0,0.001772,0.002658,0.000886,0.001152,0.000975,0.059814,0.013735,0.006646,0.023571,0.000443,0.0,0.0,0.001772

In [7]:
# Set pandas display options to show all columns
pd.set_option('display.max_columns', None)

# Display the entire DataFrame
new_df_sorted = new_df.sort_values(by='Matchweek')
new_df_sorted["Matchweek"].value_counts()

Matchweek
38    332
36    312
31    221
34    201
25    130
22    112
33    111
32    110
29    110
27     92
19     75
24     73
20     59
15     58
26     57
10     56
23     38
18     37
17     22
30     20
4       4
6       4
8       4
2       4
13      3
28      2
11      2
14      2
12      2
21      1
7       1
3       1
16      1
Name: count, dtype: int64

In [ ]:
main_df["Matches"].head(11)

In [ ]:
main_df.columns

In [ ]:
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns

# To reset to default
# pd.reset_option('display.max_rows')
# pd.reset_option('display.max_columns')

# Now display your DataFrame
main_df = main_df.sort_values(by=['Matchweek', 'season'])
main_df

In [ ]:
# Define a function to calculate the weighted form for the last 5 matches
def get_weighted_form_5(series):
    weights = [1, 2, 3, 4, 5]  # Weights for the last five matches
    if len(series) >= 5:
        return (series[-5:] * weights).sum() / sum(weights)
    return series.mean()  # Use mean if there are less than 5 elements

# Create a shifted 'result' column to calculate the form for the next match
main_df['shifted_result'] = main_df.groupby('HomeTeam')['result'].shift()

# Apply the weighted form calculation for the last 5 matches
main_df['form'] = main_df.groupby('HomeTeam')['shifted_result'].transform(
    lambda x: x.rolling(window=5, min_periods=1).apply(get_weighted_form_5, raw=True)
)

# Fill NaN values with 0 (initial matchweeks)
main_df['form'] = main_df['form'].fillna(0)

# Drop the temporary shifted_result column
main_df = main_df.drop(columns=['shifted_result'])

# Display the transformed DataFrame
main_df

In [ ]:
# Save the DataFrame to a CSV file
main_df.to_csv('clean_for_ml2.csv', index=False)