In [1]:
import pandas as pd
import datetime
matchweek_positions = pd.read_csv('/Users/merryxmm7/Documents/GitHub/Final_Project_Ironhack/Premier_league_predictor/premier_league_data.csv')
all_matches_matchweek = pd.read_csv('/Users/merryxmm7/Documents/GitHub/Final_Project_Ironhack/Premier_league_predictor/all_matches_matchweek.csv')
all_seasons_odds = pd.read_csv('/Users/merryxmm7/Documents/GitHub/Final_Project_Ironhack/Premier_league_predictor/all_seasons_odds.csv')

In [2]:
matchweek_positions

,Position,HomeTeam,Matches,Wins,Draws,Losses,Goal_Difference,Points,Matchweek,Season
0,1.0,Liverpool FC,1,1,0,0,4,3,1,2018
1,2.0,Chelsea FC,1,1,0,0,3,3,1,2018
2,3.0,AFC Bournemouth,1,1,0,0,2,3,1,2018
3,NaN,Crystal Palace,1,1,0,0,2,3,1,2018
4,NaN,Manchester City,1,1,0,0,2,3,1,2018
...,...,...,...,...,...,...,...,...,...,...
4555,16.0,Brentford FC,38,10,9,19,-9,39,38,2023
4556,17.0,Nottingham Forest,38,9,9,20,-18,32,38,2023
4557,18.0,Luton Town,38,6,8,24,-33,26,38,2023
4558,19.0,Burnley FC,38,5,9,24,-37,24,38,2023
4559,20.0,Sheffield United,38,3,7,28,-69,16,38,2023

In [3]:
#filling the missing values, since we know it is in order, its easy.
def fill_missing_positions(df):
    for i in range(len(df)):
        if pd.isna(df.loc[i, 'Position']):
            if i > 0:
                previous_position = df.loc[i - 1, 'Position']
                if previous_position == 20:
                    df.loc[i, 'Position'] = 1
                else:
                    df.loc[i, 'Position'] = previous_position + 1
            else:
                df.loc[i, 'Position'] = 1  # In case the first position is missing, start with 1

fill_missing_positions(matchweek_positions)
matchweek_positions['Position'].value_counts().sum()

4560

In [4]:
matchweek_positions['Position'] = matchweek_positions['Position'].astype(int)

In [5]:
matchweek_positions.rename(columns={'Season': 'season'}, inplace=True)

In [6]:
matchweek_positions

,Position,HomeTeam,Matches,Wins,Draws,Losses,Goal_Difference,Points,Matchweek,season
0,1,Liverpool FC,1,1,0,0,4,3,1,2018
1,2,Chelsea FC,1,1,0,0,3,3,1,2018
2,3,AFC Bournemouth,1,1,0,0,2,3,1,2018
3,4,Crystal Palace,1,1,0,0,2,3,1,2018
4,5,Manchester City,1,1,0,0,2,3,1,2018
...,...,...,...,...,...,...,...,...,...,...
4555,16,Brentford FC,38,10,9,19,-9,39,38,2023
4556,17,Nottingham Forest,38,9,9,20,-18,32,38,2023
4557,18,Luton Town,38,6,8,24,-33,26,38,2023
4558,19,Burnley FC,38,5,9,24,-37,24,38,2023
4559,20,Sheffield United,38,3,7,28,-69,16,38,2023

In [7]:
# Save the DataFrame to a CSV file
matchweek_positions.to_csv('prueba_matchweek_positions.csv', index=False)

In [8]:
###
###
###     matchweek_positions       DONE!!!
###
###

In [9]:
all_matches_matchweek.head(25)

,Date,time,comp,Matchweek,day,venue,result,gf,ga,AwayTeam,...,formation,referee,sh,sot,dist,fk,pk,pkatt,season,HomeTeam
0,2023-08-11,20:00,Premier League,1,Fri,Away,W,3,0,Burnley FC,...,4-2-3-1,Craig Pawson,17.0,8.0,13.9,0.0,0,0,2024,Manchester City
1,2023-08-19,20:00,Premier League,2,Sat,Home,W,1,0,Newcastle Utd,...,4-2-3-1,Robert Jones,14.0,4.0,17.9,0.0,0,0,2024,Manchester City
2,2023-08-27,14:00,Premier League,3,Sun,Away,W,2,1,Sheffield Utd,...,4-2-3-1,Jarred Gillett,29.0,9.0,17.3,2.0,0,1,2024,Manchester City
3,2023-09-02,15:00,Premier League,4,Sat,Home,W,5,1,Fulham FC,...,4-2-3-1,Michael Oliver,6.0,4.0,14.8,0.0,1,1,2024,Manchester City
4,2023-09-16,15:00,Premier League,5,Sat,Away,W,3,1,West Ham United,...,4-2-3-1,Andy Madley,29.0,13.0,16.4,1.0,0,0,2024,Manchester City
5,2023-09-23,15:00,Premier League,6,Sat,Home,W,2,0,Nott'ham Forest,...,4-2-3-1,Anthony Taylor,7.0,4.0,17.2,2.0,0,0,2024,Manchester City
6,2023-09-30,15:00,Premier League,7,Sat,Away,L,1,2,Wolverhampton Wanderers,...,4-2-3-1,Craig Pawson,23.0,8.0,19.3,1.0,0,0,2024,Manchester City
7,2023-10-08,16:30,Premier League,8,Sun,Away,L,0,1,Arsenal FC,...,4-3-3,Michael Oliver,4.0,0.0,14.9,0.0,0,0,2024,Manchester City
8,2023-10-21,15:00,Premier League,9,Sat,Home,W,2,1,Brighton & Hove Albion,...,3-2-4-1,Robert Jones,10.0,5.0,18.8,1.0,0,0,2024,Manchester City
9,2023-10-29,15:30,Premier League,10,Sun,Away,W,3,0,Manchester Utd,...,4-2-3-1,Paul Tierney,20.0,9.0,17.2,2.0,1,1,2024,Manchester City
10,2023-11-04,15:00,Premier League,11,Sat,Home,W,6,1,AFC Bournemouth,...,3-4-3,Craig Pawson,21.0,8.0,16.4,0.0,0,0,2024,Manchester City
11,2023-11-12,16:30,Premier League,12,Sun,Away,D,4,4,Chelsea FC,...,3-2-4-1,Anthony Taylor,14.0,9.0,16.6,1.0,1,1,2024,Manchester City
12,2023-11-25,12:30,Premier League,13,Sat,Home,D,1,1,Liverpool FC,...,3-2-4-1,Chris Kavanagh,16.0,5.0,16.3,1.0,0,0,2024,Manchester City
13,2023-12-03,16:30,Premier League,14,Sun,Home,D,3,3,Tottenham Hotspur,...,3-2-4-1,Simon Hooper,17.0,4.0,13.4,0.0,0,0,2024,Manchester City
14,2023-12-06,20:15,Premier League,15,Wed,Away,L,0,1,Aston Villa,...,3-2-4-1,John Brooks,2.0,2.0,7.4,0.0,0,0,2024,Manchester City
15,2023-12-10,14:00,Premier League,16,Sun,Away,W,2,1,Luton Town,...,4-2-3-1,Tim Robinson,18.0,6.0,18.7,1.0,0,0,2024,Manchester City
16,2023-12-16,15:00,Premier League,17,Sat,Home,D,2,2,Crystal Palace,...,4-2-3-1,Paul Tierney,19.0,9.0,18.2,0.0,0,0,2024,Manchester City
17,2023-12-27,20:15,Premier League,19,Wed,Away,W,3,1,Everton FC,...,4-2-3-1,John Brooks,22.0,8.0,19.5,1.0,1,1,2024,Manchester City
18,2023-12-30,15:00,Premier League,20,Sat,Home,W,2,0,Sheffield Utd,...,4-2-3-1,David Coote,18.0,4.0,17.4,0.0,0,0,2024,Manchester City
19,2024-01-13,17:30,Premier League,21,Sat,Away,W,3,2,Newcastle Utd,...,4-2-3-1,Chris Kavanagh,27.0,11.0,19.3,2.0,0,0,2024,Manchester City
20,2024-01-31,19:30,Premier League,22,Wed,Home,W,3,1,Burnley FC,...,4-2-3-1,Samuel Barrott,14.0,4.0,15.8,1.0,0,0,2024,Manchester City
21,2024-02-05,20:00,Premier League,23,Mon,Away,W,3,1,Brentford FC,...,4-1-4-1,Jarred Gillett,25.0,15.0,19.2,0.0,0,0,2024,Manchester City
22,2024-02-10,12:30,Premier League,24,Sat,Home,W,2,0,Everton FC,...,4-1-4-1,John Brooks,19.0,3.0,17.4,0.0,0,0,2024,Manchester City
23,2024-02-17,17:30,Premier League,25,Sat,Home,D,1,1,Chelsea FC,...,4-1-4-1,Andy Madley,31.0,5.0,15.9,1.0,0,0,2024,Manchester City
24,2024-02-20,19:30,Premier League,18,Tue,Home,W,1,0,Brentford FC,...,4-2-3-1,Darren England,25.0,10.0,17.6,0.0,0,0,2024,Manchester City

In [10]:
all_matches_matchweek["season"].value_counts()

season
2024    760
2023    760
2022    760
2021    760
2020    760
2019    760
2018    760
Name: count, dtype: int64

In [11]:
all_matches_matchweek = all_matches_matchweek[all_matches_matchweek['season'] != 2018]

# Subtract 1 from each value in the 'season' column to match the other dataframes formats
all_matches_matchweek.loc[:, 'season'] = all_matches_matchweek['season'] - 1

# Print the 'season' value counts to verify
all_matches_matchweek['season'].value_counts()

season
2023    760
2022    760
2021    760
2020    760
2019    760
2018    760
Name: count, dtype: int64

In [12]:
# Convert 'Date' to datetime
all_matches_matchweek.loc[:, 'Date'] = pd.to_datetime(all_matches_matchweek['Date'])

# Map days of the week to numerical values
day_mapping = {'Mon': 1, 'Tue': 2, 'Wed': 3, 'Thu': 4, 'Fri': 5, 'Sat': 6, 'Sun': 7}
all_matches_matchweek.loc[:, 'day'] = all_matches_matchweek['day'].map(day_mapping)

In [13]:
all_matches_matchweek = all_matches_matchweek.drop(columns=['comp',"formation", "captain","referee"])

In [14]:
all_matches_matchweek['Date'] = pd.to_datetime(all_matches_matchweek['Date'])

In [15]:
# Function to convert time strings to datetime.time
# Function to convert time strings to datetime.time
def convert_to_time(time_str):
    if isinstance(time_str, datetime.time):
        return time_str
    try:
        if len(time_str) == 5:  # HH:MM format
            return datetime.datetime.strptime(time_str, '%H:%M').time()
        elif len(time_str) == 8:  # HH:MM:SS format
            return datetime.datetime.strptime(time_str, '%H:%M:%S').time()
    except ValueError as e:
        print(f"Error parsing time: {e}")
    return None

# Apply the function to the 'time' column
all_matches_matchweek['time'] = all_matches_matchweek['time'].apply(convert_to_time)

In [16]:
all_matches_matchweek['time'] = pd.to_datetime(all_matches_matchweek['time'], format='%H:%M:%S').dt.time

In [17]:
# missed 2 NaN values. fill them with the mode
# Calculate the mode of the "dist" column
dist_mode = all_matches_matchweek["dist"].mode()[0]  # Get the first mode value

# Fill NaN values in the "dist" column with the mode
all_matches_matchweek["dist"].fillna(dist_mode, inplace=True)

# Print the DataFrame with NaN values filled
all_matches_matchweek.isna().sum()

Date         0
time         0
Matchweek    0
day          0
venue        0
result       0
gf           0
ga           0
AwayTeam     0
xg           0
xga          0
poss         0
sh           0
sot          0
dist         0
fk           0
pk           0
pkatt        0
season       0
HomeTeam     0
dtype: int64

In [18]:
# Sort the DataFrame by Date
all_matches_matchweek = all_matches_matchweek.sort_values(by=['Date', 'HomeTeam'])

## merging with away

In [19]:
# have to chop to have the same rows and the same matches. Easily done if only taking the matches where
# HomeTeam was at Home
all_matches_AWAY = all_matches_matchweek[all_matches_matchweek['venue'] != 'Home']

# Reset the index after filtering
all_matches_AWAY.reset_index(drop=True, inplace=True)

# List of columns to exclude from renaming
exclude_cols = ['Date', 'time', 'Matchweek', 'day', 'venue', 'AwayTeam', 'season', 'HomeTeam']

# Rename columns
all_matches_AWAY.columns = [
    f"away_{col}" if col not in exclude_cols else col 
    for col in all_matches_AWAY.columns
]
# create the goal_difference column for the away Team
all_matches_AWAY['away_Goal_Difference'] = all_matches_AWAY['away_gf'] - all_matches_AWAY['away_ga']

#since the logic in the table is inverse we change the name of the columns to ahve the appropiate values for the teams
all_matches_AWAY.rename(columns={'AwayTeam': 'TempHomeTeam', 'HomeTeam': 'AwayTeam'}, inplace=True)
all_matches_AWAY.rename(columns={'TempHomeTeam': 'HomeTeam'}, inplace=True)

# Display the modified DataFrame
all_matches_AWAY

/var/folders/z5/cx4ddsg557q0lqzd5939yrkh0000gn/T/ipykernel_87016/3350341208.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_matches_AWAY['away_Goal_Difference'] = all_matches_AWAY['away_gf'] - all_matches_AWAY['away_ga']
/var/folders/z5/cx4ddsg557q0lqzd5939yrkh0000gn/T/ipykernel_87016/3350341208.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_matches_AWAY.rename(columns={'AwayTeam': 'TempHomeTeam', 'HomeTeam': 'AwayTeam'}, inplace=True)
/var/folders/z5/cx4ddsg557q0lqzd5939yrkh0000gn/T/ipykernel_87016/3350341208.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_matches_AWAY.rename(columns={'TempHomeTeam': 'HomeTeam'}, inplace=True)

,Date,time,Matchweek,day,venue,away_result,away_gf,away_ga,HomeTeam,away_xg,...,away_poss,away_sh,away_sot,away_dist,away_fk,away_pk,away_pkatt,season,AwayTeam,away_Goal_Difference
0,2018-08-10,20:00:00,1,5,Away,L,1,2,Manchester Utd,1.8,...,53.0,13.0,4.0,20.6,1.0,0,0,2018,Leicester City,-1
1,2018-08-11,15:00:00,1,6,Away,L,0,2,Watford FC,0.3,...,47.0,6.0,0.0,18.1,1.0,0,0,2018,Brighton and Hove Albion,-2
2,2018-08-11,15:00:00,1,6,Away,L,0,2,AFC Bournemouth,1.4,...,37.0,10.0,1.0,13.1,1.0,0,0,2018,Cardiff City,-2
3,2018-08-11,15:00:00,1,6,Away,W,3,0,Huddersfield Town,1.9,...,62.0,12.0,3.0,17.7,2.0,1,1,2018,Chelsea FC,3
4,2018-08-11,15:00:00,1,6,Away,W,2,0,Fulham FC,1.0,...,35.0,12.0,10.0,17.8,0.0,0,0,2018,Crystal Palace,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2275,2024-05-19,16:00:00,38,7,Away,W,4,2,Brentford FC,3.4,...,46.0,12.0,7.0,15.4,2.0,0,0,2023,Newcastle United,2
2276,2024-05-19,16:00:00,38,7,Away,W,2,1,Burnley FC,1.7,...,28.0,12.0,6.0,17.2,0.0,0,0,2023,Nottingham Forest,1
2277,2024-05-19,16:00:00,38,7,Away,W,3,0,Sheffield Utd,3.1,...,75.0,18.0,9.0,14.4,1.0,0,0,2023,Tottenham Hotspur,3
2278,2024-05-19,16:00:00,38,7,Away,L,1,3,Manchester City,0.4,...,29.0,3.0,2.0,10.3,0.0,0,0,2023,West Ham United,-2
2279,2024-05-19,16:00:00,38,7,Away,L,0,2,Liverpool FC,0.5,...,33.0,4.0,2.0,19.0,1.0,0,0,2023,Wolverhampton Wanderers,-2

In [20]:
all_matches_AWAY['away_Win'] = (all_matches_AWAY['away_result'] == 'W').astype(int)
all_matches_AWAY['away_Draw'] = (all_matches_AWAY['away_result'] == 'D').astype(int)
all_matches_AWAY['away_Loss'] = (all_matches_AWAY['away_result'] == 'L').astype(int)

# Update 'away_result' column to 1 if it was 'W' or 0 if it wasn't
all_matches_AWAY['away_result'] = (all_matches_AWAY['away_result'] == 'W').astype(int)

/var/folders/z5/cx4ddsg557q0lqzd5939yrkh0000gn/T/ipykernel_87016/3886305344.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_matches_AWAY['away_Win'] = (all_matches_AWAY['away_result'] == 'W').astype(int)
/var/folders/z5/cx4ddsg557q0lqzd5939yrkh0000gn/T/ipykernel_87016/3886305344.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_matches_AWAY['away_Draw'] = (all_matches_AWAY['away_result'] == 'D').astype(int)
/var/folders/z5/cx4ddsg557q0lqzd5939yrkh0000gn/T/ipykernel_87016/3886305344.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_matches_AWAY['away_Loss'] = (all_matches_AWAY['away_result'] == 'L').astype(int)
/var/folders/z5/cx4ddsg557q0lqzd5939yrkh0000gn/T/ipykernel_87016/3886305344.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_matches_AWAY['away_result'] = (all_matches_AWAY['away_result'] == 'W').astype(int)

In [21]:
merged_away_df = pd.concat([all_seasons_odds, all_matches_AWAY] , axis =1)
merged_away_df

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,away_dist,away_fk,away_pk,away_pkatt,season,AwayTeam,away_Goal_Difference,away_Win,away_Draw,away_Loss
0,2018-08-10,Manchester United,Leicester City,2,1,H,1,0,H,A Marriner,...,20.6,1.0,0,0,2018,Leicester City,-1,0,0,1
1,2018-08-11,AFC Bournemouth,Cardiff City,2,0,H,1,0,H,K Friend,...,18.1,1.0,0,0,2018,Brighton and Hove Albion,-2,0,0,1
2,2018-08-11,Fulham FC,Crystal Palace,0,2,A,0,1,A,M Dean,...,13.1,1.0,0,0,2018,Cardiff City,-2,0,0,1
3,2018-08-11,Huddersfield Town,Chelsea FC,0,3,A,0,2,A,C Kavanagh,...,17.7,2.0,1,1,2018,Chelsea FC,3,1,0,0
4,2018-08-11,Newcastle United,Tottenham Hotspur,1,2,A,1,2,A,M Atkinson,...,17.8,0.0,0,0,2018,Crystal Palace,2,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2275,2024-05-19,Crystal Palace,Aston Villa,5,0,H,2,0,H,D Bond,...,15.4,2.0,0,0,2023,Newcastle United,2,1,0,0
2276,2024-05-19,Liverpool FC,Wolverhampton Wanderers,2,0,H,2,0,H,C Kavanagh,...,17.2,0.0,0,0,2023,Nottingham Forest,1,1,0,0
2277,2024-05-19,Luton Town,Fulham FC,2,4,A,1,2,A,M Donohue,...,14.4,1.0,0,0,2023,Tottenham Hotspur,3,1,0,0
2278,2024-05-19,Manchester City,West Ham United,3,1,H,2,1,H,J Brooks,...,10.3,0.0,0,0,2023,West Ham United,-2,0,0,1
2279,2024-05-19,Sheffield United,Tottenham Hotspur,0,3,A,0,1,A,A Madley,...,19.0,1.0,0,0,2023,Wolverhampton Wanderers,-2,0,0,1

In [22]:
merged_away_df = merged_away_df.loc[:, ~merged_away_df.columns.duplicated()]
merged_away_df

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,away_sh,away_sot,away_dist,away_fk,away_pk,away_pkatt,away_Goal_Difference,away_Win,away_Draw,away_Loss
0,2018-08-10,Manchester United,Leicester City,2,1,H,1,0,H,A Marriner,...,13.0,4.0,20.6,1.0,0,0,-1,0,0,1
1,2018-08-11,AFC Bournemouth,Cardiff City,2,0,H,1,0,H,K Friend,...,6.0,0.0,18.1,1.0,0,0,-2,0,0,1
2,2018-08-11,Fulham FC,Crystal Palace,0,2,A,0,1,A,M Dean,...,10.0,1.0,13.1,1.0,0,0,-2,0,0,1
3,2018-08-11,Huddersfield Town,Chelsea FC,0,3,A,0,2,A,C Kavanagh,...,12.0,3.0,17.7,2.0,1,1,3,1,0,0
4,2018-08-11,Newcastle United,Tottenham Hotspur,1,2,A,1,2,A,M Atkinson,...,12.0,10.0,17.8,0.0,0,0,2,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2275,2024-05-19,Crystal Palace,Aston Villa,5,0,H,2,0,H,D Bond,...,12.0,7.0,15.4,2.0,0,0,2,1,0,0
2276,2024-05-19,Liverpool FC,Wolverhampton Wanderers,2,0,H,2,0,H,C Kavanagh,...,12.0,6.0,17.2,0.0,0,0,1,1,0,0
2277,2024-05-19,Luton Town,Fulham FC,2,4,A,1,2,A,M Donohue,...,18.0,9.0,14.4,1.0,0,0,3,1,0,0
2278,2024-05-19,Manchester City,West Ham United,3,1,H,2,1,H,J Brooks,...,3.0,2.0,10.3,0.0,0,0,-2,0,0,1
2279,2024-05-19,Sheffield United,Tottenham Hotspur,0,3,A,0,1,A,A Madley,...,4.0,2.0,19.0,1.0,0,0,-2,0,0,1

In [23]:
matchweek_positions.rename(columns={'HomeTeam': 'AwayTeam'}, inplace=True)

In [24]:
merged_away_df.columns

Index(['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG',
       'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC',
       'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'season', 'time',
       'Matchweek', 'day', 'venue', 'away_result', 'away_gf', 'away_ga',
       'away_xg', 'away_xga', 'away_poss', 'away_sh', 'away_sot', 'away_dist',
       'away_fk', 'away_pk', 'away_pkatt', 'away_Goal_Difference', 'away_Win',
       'away_Draw', 'away_Loss'],
      dtype='object')

In [25]:
merged_complete_away_points = pd.merge(
    matchweek_positions.drop(columns=['Wins', 'Draws', 'Losses', 'Goal_Difference']),
    merged_away_df,
    left_on=['AwayTeam', 'Matchweek', 'season'],
    right_on=['AwayTeam', 'Matchweek', 'season']
)
merged_complete_away_points.rename(columns={'Position': 'away_Position'}, inplace=True)
merged_complete_away_points.rename(columns={'Points': 'away_Points'}, inplace=True)
merged_complete_away_points

,away_Position,AwayTeam,Matches,away_Points,Matchweek,season,Date,HomeTeam,FTHG,FTAG,...,away_sh,away_sot,away_dist,away_fk,away_pk,away_pkatt,away_Goal_Difference,away_Win,away_Draw,away_Loss
0,2,Chelsea FC,1,3,1,2018,2018-08-11,Huddersfield Town,0,3,...,12.0,3.0,17.7,2.0,1,1,3,1,0,0
1,4,Crystal Palace,1,3,1,2018,2018-08-11,Fulham FC,0,2,...,10.0,1.0,13.1,1.0,0,0,-2,0,0,1
2,5,Manchester City,1,3,1,2018,2018-08-12,Arsenal FC,0,2,...,16.0,6.0,17.5,1.0,0,0,0,0,1,0
3,8,Tottenham Hotspur,1,3,1,2018,2018-08-11,Newcastle United,1,2,...,12.0,10.0,17.8,0.0,0,0,2,1,0,0
4,9,Everton FC,1,1,1,2018,2018-08-11,Wolverhampton Wanderers,2,2,...,15.0,5.0,15.0,1.0,0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2275,12,AFC Bournemouth,38,48,38,2023,2024-05-19,Chelsea FC,2,1,...,11.0,4.0,17.0,0.0,0,0,2,1,0,0
2276,13,Fulham FC,38,47,38,2023,2024-05-19,Luton Town,2,4,...,18.0,9.0,14.4,1.0,0,0,3,1,0,0
2277,14,Wolverhampton Wanderers,38,46,38,2023,2024-05-19,Liverpool FC,2,0,...,12.0,6.0,17.2,0.0,0,0,1,1,0,0
2278,15,Everton FC,38,40,38,2023,2024-05-19,Arsenal FC,2,1,...,22.0,5.0,16.8,0.0,0,0,-1,0,0,1
2279,17,Nottingham Forest,38,32,38,2023,2024-05-19,Burnley FC,1,2,...,16.0,8.0,21.6,2.0,0,0,2,1,0,0

In [26]:
####################

In [27]:
merged_complete_away_points = merged_complete_away_points[['Date', 'AwayTeam', 'season', 'away_Points', 'away_Position']]
merged_complete_away_points

            Date                 AwayTeam  season  away_Points  away_Position
0     2018-08-11               Chelsea FC    2018            3              2
1     2018-08-11           Crystal Palace    2018            3              4
2     2018-08-12          Manchester City    2018            3              5
3     2018-08-11        Tottenham Hotspur    2018            3              8
4     2018-08-11               Everton FC    2018            1              9
...          ...                      ...     ...          ...            ...
2275  2024-05-19          AFC Bournemouth    2023           48             12
2276  2024-05-19                Fulham FC    2023           47             13
2277  2024-05-19  Wolverhampton Wanderers    2023           46             14
2278  2024-05-19               Everton FC    2023           40             15
2279  2024-05-19        Nottingham Forest    2023           32             17

[2280 rows x 5 columns]

## End of merge with away

In [28]:
# have to chop to have the same rows and the same matches. Easily done if only taking the matches where
matchweek_positions.rename(columns={'AwayTeam': 'HomeTeam'}, inplace=True)
# HomeTeam was at Home
all_matches_matchweek = all_matches_matchweek[all_matches_matchweek['venue'] != 'Away']

# Reset the index after filtering
all_matches_matchweek.reset_index(drop=True, inplace=True)

# Display the modified DataFrame
all_matches_matchweek

,Date,time,Matchweek,day,venue,result,gf,ga,AwayTeam,xg,xga,poss,sh,sot,dist,fk,pk,pkatt,season,HomeTeam
0,2018-08-10,20:00:00,1,5,Home,W,2,1,Leicester City,1.5,1.8,47.0,7.0,5.0,20.8,0.0,1,1,2018,Manchester United
1,2018-08-11,15:00:00,1,6,Home,W,2,0,Cardiff City,2.2,1.4,63.0,11.0,3.0,16.7,0.0,0,1,2018,AFC Bournemouth
2,2018-08-11,15:00:00,1,6,Home,L,0,2,Crystal Palace,0.7,1.0,65.0,15.0,6.0,20.4,1.0,0,0,2018,Fulham FC
3,2018-08-11,15:00:00,1,6,Home,L,0,3,Chelsea FC,0.3,1.9,38.0,6.0,1.0,18.4,0.0,0,0,2018,Huddersfield Town
4,2018-08-11,12:30:00,1,6,Home,L,1,2,Tottenham Hotspur,1.0,2.0,42.0,15.0,2.0,17.7,0.0,0,0,2018,Newcastle United
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2275,2024-05-19,16:00:00,38,7,Home,W,5,0,Aston Villa,2.5,0.9,54.0,15.0,9.0,16.8,0.0,0,0,2023,Crystal Palace
2276,2024-05-19,16:00:00,38,7,Home,W,2,0,Wolverhampton Wanderers,4.5,0.5,67.0,36.0,13.0,14.8,0.0,0,0,2023,Liverpool FC
2277,2024-05-19,16:00:00,38,7,Home,L,2,4,Fulham FC,2.0,1.1,41.0,14.0,5.0,19.3,2.0,1,1,2023,Luton Town
2278,2024-05-19,16:00:00,38,7,Home,W,3,1,West Ham United,1.9,0.4,71.0,28.0,12.0,17.9,2.0,0,0,2023,Manchester City
2279,2024-05-19,16:00:00,38,7,Home,L,0,3,Tottenham Hotspur,1.0,3.1,25.0,6.0,1.0,18.0,1.0,0,0,2023,Sheffield United

In [29]:
# Save the DataFrame to a CSV file
all_matches_matchweek.to_csv('prueba_matches_matchweek.csv', index=False)

In [30]:
###
###
###     all_matches_matchweek       DONE!!!
###
###

In [31]:
all_seasons_odds

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,season
0,2018-08-10,Manchester United,Leicester City,2,1,H,1,0,H,A Marriner,...,2,5,2,1,0,0,1.57,3.90,7.50,2018
1,2018-08-11,AFC Bournemouth,Cardiff City,2,0,H,1,0,H,K Friend,...,7,4,1,1,0,0,1.90,3.60,4.50,2018
2,2018-08-11,Fulham FC,Crystal Palace,0,2,A,0,1,A,M Dean,...,5,5,1,2,0,0,2.50,3.40,3.00,2018
3,2018-08-11,Huddersfield Town,Chelsea FC,0,3,A,0,2,A,C Kavanagh,...,2,5,2,1,0,0,6.50,4.00,1.61,2018
4,2018-08-11,Newcastle United,Tottenham Hotspur,1,2,A,1,2,A,M Atkinson,...,3,5,2,2,0,0,3.90,3.50,2.04,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2275,2024-05-19,Crystal Palace,Aston Villa,5,0,H,2,0,H,D Bond,...,2,4,1,4,0,0,1.85,4.33,3.60,2023
2276,2024-05-19,Liverpool FC,Wolverhampton Wanderers,2,0,H,2,0,H,C Kavanagh,...,10,2,1,1,0,1,1.17,8.00,15.00,2023
2277,2024-05-19,Luton Town,Fulham FC,2,4,A,1,2,A,M Donohue,...,4,4,5,4,0,0,2.90,3.90,2.20,2023
2278,2024-05-19,Manchester City,West Ham United,3,1,H,2,1,H,J Brooks,...,11,2,0,1,0,0,1.08,12.00,21.00,2023
2279,2024-05-19,Sheffield United,Tottenham Hotspur,0,3,A,0,1,A,A Madley,...,2,6,2,0,0,0,7.00,6.00,1.33,2023

In [32]:
#convert the Date column to datetime type conserving the format
all_seasons_odds["Date"] = pd.to_datetime(all_seasons_odds["Date"], format="%Y-%m-%d")

In [33]:
all_seasons_odds.dtypes

Date        datetime64[ns]
HomeTeam            object
AwayTeam            object
FTHG                 int64
FTAG                 int64
FTR                 object
HTHG                 int64
HTAG                 int64
HTR                 object
Referee             object
HS                   int64
AS                   int64
HST                  int64
AST                  int64
HF                   int64
AF                   int64
HC                   int64
AC                   int64
HY                   int64
AY                   int64
HR                   int64
AR                   int64
B365H              float64
B365D              float64
B365A              float64
season               int64
dtype: object

In [34]:
# Rename the columns
all_seasons_odds.rename(columns={'FTHG': 'gf', 'FTAG': 'ga'}, inplace=True)

In [35]:
all_seasons_odds

,Date,HomeTeam,AwayTeam,gf,ga,FTR,HTHG,HTAG,HTR,Referee,...,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,season
0,2018-08-10,Manchester United,Leicester City,2,1,H,1,0,H,A Marriner,...,2,5,2,1,0,0,1.57,3.90,7.50,2018
1,2018-08-11,AFC Bournemouth,Cardiff City,2,0,H,1,0,H,K Friend,...,7,4,1,1,0,0,1.90,3.60,4.50,2018
2,2018-08-11,Fulham FC,Crystal Palace,0,2,A,0,1,A,M Dean,...,5,5,1,2,0,0,2.50,3.40,3.00,2018
3,2018-08-11,Huddersfield Town,Chelsea FC,0,3,A,0,2,A,C Kavanagh,...,2,5,2,1,0,0,6.50,4.00,1.61,2018
4,2018-08-11,Newcastle United,Tottenham Hotspur,1,2,A,1,2,A,M Atkinson,...,3,5,2,2,0,0,3.90,3.50,2.04,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2275,2024-05-19,Crystal Palace,Aston Villa,5,0,H,2,0,H,D Bond,...,2,4,1,4,0,0,1.85,4.33,3.60,2023
2276,2024-05-19,Liverpool FC,Wolverhampton Wanderers,2,0,H,2,0,H,C Kavanagh,...,10,2,1,1,0,1,1.17,8.00,15.00,2023
2277,2024-05-19,Luton Town,Fulham FC,2,4,A,1,2,A,M Donohue,...,4,4,5,4,0,0,2.90,3.90,2.20,2023
2278,2024-05-19,Manchester City,West Ham United,3,1,H,2,1,H,J Brooks,...,11,2,0,1,0,0,1.08,12.00,21.00,2023
2279,2024-05-19,Sheffield United,Tottenham Hotspur,0,3,A,0,1,A,A Madley,...,2,6,2,0,0,0,7.00,6.00,1.33,2023

In [36]:
all_seasons_odds.columns

Index(['Date', 'HomeTeam', 'AwayTeam', 'gf', 'ga', 'FTR', 'HTHG', 'HTAG',
       'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC',
       'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'season'],
      dtype='object')

In [37]:
# Save the DataFrame to a CSV file
all_seasons_odds.to_csv('prueba_matches_odds.csv', index=False)

In [38]:
###
###
###     all_seasons_odds       DONE!!!
###
###

In [39]:
###
### merging all_seasons_odds & all_matches_matchweek
###

In [40]:
merged_df = pd.concat([all_seasons_odds, all_matches_matchweek] , axis =1)

In [41]:
merged_df

,Date,HomeTeam,AwayTeam,gf,ga,FTR,HTHG,HTAG,HTR,Referee,...,xga,poss,sh,sot,dist,fk,pk,pkatt,season,HomeTeam
0,2018-08-10,Manchester United,Leicester City,2,1,H,1,0,H,A Marriner,...,1.8,47.0,7.0,5.0,20.8,0.0,1,1,2018,Manchester United
1,2018-08-11,AFC Bournemouth,Cardiff City,2,0,H,1,0,H,K Friend,...,1.4,63.0,11.0,3.0,16.7,0.0,0,1,2018,AFC Bournemouth
2,2018-08-11,Fulham FC,Crystal Palace,0,2,A,0,1,A,M Dean,...,1.0,65.0,15.0,6.0,20.4,1.0,0,0,2018,Fulham FC
3,2018-08-11,Huddersfield Town,Chelsea FC,0,3,A,0,2,A,C Kavanagh,...,1.9,38.0,6.0,1.0,18.4,0.0,0,0,2018,Huddersfield Town
4,2018-08-11,Newcastle United,Tottenham Hotspur,1,2,A,1,2,A,M Atkinson,...,2.0,42.0,15.0,2.0,17.7,0.0,0,0,2018,Newcastle United
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2275,2024-05-19,Crystal Palace,Aston Villa,5,0,H,2,0,H,D Bond,...,0.9,54.0,15.0,9.0,16.8,0.0,0,0,2023,Crystal Palace
2276,2024-05-19,Liverpool FC,Wolverhampton Wanderers,2,0,H,2,0,H,C Kavanagh,...,0.5,67.0,36.0,13.0,14.8,0.0,0,0,2023,Liverpool FC
2277,2024-05-19,Luton Town,Fulham FC,2,4,A,1,2,A,M Donohue,...,1.1,41.0,14.0,5.0,19.3,2.0,1,1,2023,Luton Town
2278,2024-05-19,Manchester City,West Ham United,3,1,H,2,1,H,J Brooks,...,0.4,71.0,28.0,12.0,17.9,2.0,0,0,2023,Manchester City
2279,2024-05-19,Sheffield United,Tottenham Hotspur,0,3,A,0,1,A,A Madley,...,3.1,25.0,6.0,1.0,18.0,1.0,0,0,2023,Sheffield United

## merge merged_df and merged_complete_away to have complete away and home stats. Only missing the points

In [42]:
merged_away_df.columns

Index(['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG',
       'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC',
       'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'season', 'time',
       'Matchweek', 'day', 'venue', 'away_result', 'away_gf', 'away_ga',
       'away_xg', 'away_xga', 'away_poss', 'away_sh', 'away_sot', 'away_dist',
       'away_fk', 'away_pk', 'away_pkatt', 'away_Goal_Difference', 'away_Win',
       'away_Draw', 'away_Loss'],
      dtype='object')

In [43]:
# Remove the duplicate 'Date' column from merged_df
merged_df = merged_df.loc[:, ~merged_df.columns.duplicated()]

# Ensure the Date columns are of datetime type
merged_df['Date'] = pd.to_datetime(merged_df['Date'])
merged_away_df['Date'] = pd.to_datetime(merged_away_df['Date'])

# Sort both DataFrames by Date and HomeTeam for merged_df, and Date and AwayTeam for merged_away_df
merged_df = merged_df.sort_values(by=['Date', 'HomeTeam'])
merged_away_df = merged_away_df.sort_values(by=['Date', 'AwayTeam'])

# Perform the merge on the specified columns
home_and_away = pd.merge(
    merged_df,
    merged_away_df,
    on=['HomeTeam', 'AwayTeam', 'Date', 'season', 'Matchweek'],
    suffixes=('_df', '_away')  # To handle any potential column name clashes
)
home_and_away

/var/folders/z5/cx4ddsg557q0lqzd5939yrkh0000gn/T/ipykernel_87016/28895968.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df['Date'] = pd.to_datetime(merged_df['Date'])
/var/folders/z5/cx4ddsg557q0lqzd5939yrkh0000gn/T/ipykernel_87016/28895968.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_away_df['Date'] = pd.to_datetime(merged_away_df['Date'])

,Date,HomeTeam,AwayTeam,gf,ga,FTR_df,HTHG_df,HTAG_df,HTR_df,Referee_df,...,away_sh,away_sot,away_dist,away_fk,away_pk,away_pkatt,away_Goal_Difference,away_Win,away_Draw,away_Loss
0,2018-08-10,Manchester United,Leicester City,2,1,H,1,0,H,A Marriner,...,13.0,4.0,20.6,1.0,0,0,-1,0,0,1
1,2018-08-11,AFC Bournemouth,Cardiff City,2,0,H,1,0,H,K Friend,...,6.0,0.0,18.1,1.0,0,0,-2,0,0,1
2,2018-08-11,Fulham FC,Crystal Palace,0,2,A,0,1,A,M Dean,...,10.0,1.0,13.1,1.0,0,0,-2,0,0,1
3,2018-08-11,Huddersfield Town,Chelsea FC,0,3,A,0,2,A,C Kavanagh,...,12.0,3.0,17.7,2.0,1,1,3,1,0,0
4,2018-08-11,Newcastle United,Tottenham Hotspur,1,2,A,1,2,A,M Atkinson,...,12.0,10.0,17.8,0.0,0,0,2,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2252,2024-05-19,Crystal Palace,Aston Villa,5,0,H,2,0,H,D Bond,...,12.0,7.0,15.4,2.0,0,0,2,1,0,0
2253,2024-05-19,Liverpool FC,Wolverhampton Wanderers,2,0,H,2,0,H,C Kavanagh,...,12.0,6.0,17.2,0.0,0,0,1,1,0,0
2254,2024-05-19,Luton Town,Fulham FC,2,4,A,1,2,A,M Donohue,...,18.0,9.0,14.4,1.0,0,0,3,1,0,0
2255,2024-05-19,Manchester City,West Ham United,3,1,H,2,1,H,J Brooks,...,3.0,2.0,10.3,0.0,0,0,-2,0,0,1
2256,2024-05-19,Sheffield United,Tottenham Hotspur,0,3,A,0,1,A,A Madley,...,4.0,2.0,19.0,1.0,0,0,-2,0,0,1

In [44]:
home_and_away['Date'] = pd.to_datetime(home_and_away['Date'])
merged_complete_away_points['Date'] = pd.to_datetime(merged_complete_away_points['Date'])

# Check the data types of the Date columns
print(home_and_away['Date'].dtype)
print(merged_complete_away_points['Date'].dtype)

/var/folders/z5/cx4ddsg557q0lqzd5939yrkh0000gn/T/ipykernel_87016/2636581401.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_complete_away_points['Date'] = pd.to_datetime(merged_complete_away_points['Date'])

datetime64[ns]
datetime64[ns]

In [45]:
# use chat gpt to merge: 
# Sort both DataFrames by Date and AwayTeam
home_and_away = home_and_away.sort_values(by=['Date', 'AwayTeam'])
merged_complete_away_points = merged_complete_away_points.sort_values(by=['Date', 'AwayTeam'])

# Remove duplicate columns from home_and_away if any
home_and_away = home_and_away.loc[:, ~home_and_away.columns.duplicated()]

# Perform the merge on the specified columns
final_merged_df = pd.merge(
    home_and_away,
    merged_complete_away_points,
    on=['AwayTeam', 'Date', 'season'],
    suffixes=('_home_and_away', '_complete_away_points')  # To handle any potential column name clashes
)

final_merged_df

,Date,HomeTeam,AwayTeam,gf,ga,FTR_df,HTHG_df,HTAG_df,HTR_df,Referee_df,...,away_dist,away_fk,away_pk,away_pkatt,away_Goal_Difference,away_Win,away_Draw,away_Loss,away_Points,away_Position
0,2018-08-10,Manchester United,Leicester City,2,1,H,1,0,H,A Marriner,...,20.6,1.0,0,0,-1,0,0,1,0,13
1,2018-08-11,Watford FC,Brighton & Hove Albion,2,0,H,1,0,H,J Moss,...,11.5,0.0,0,0,0,0,1,0,0,16
2,2018-08-11,AFC Bournemouth,Cardiff City,2,0,H,1,0,H,K Friend,...,18.1,1.0,0,0,-2,0,0,1,0,17
3,2018-08-11,Huddersfield Town,Chelsea FC,0,3,A,0,2,A,C Kavanagh,...,17.7,2.0,1,1,3,1,0,0,3,2
4,2018-08-11,Fulham FC,Crystal Palace,0,2,A,0,1,A,M Dean,...,13.1,1.0,0,0,-2,0,0,1,3,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2252,2024-05-19,Brentford FC,Newcastle United,2,4,A,0,3,A,S Hooper,...,13.8,0.0,0,0,-5,0,0,1,60,7
2253,2024-05-19,Burnley FC,Nottingham Forest,1,2,A,0,2,A,G Scott,...,21.6,2.0,0,0,2,1,0,0,32,17
2254,2024-05-19,Sheffield United,Tottenham Hotspur,0,3,A,0,1,A,A Madley,...,19.0,1.0,0,0,-2,0,0,1,66,5
2255,2024-05-19,Manchester City,West Ham United,3,1,H,2,1,H,J Brooks,...,10.3,0.0,0,0,-2,0,0,1,52,9
2256,2024-05-19,Liverpool FC,Wolverhampton Wanderers,2,0,H,2,0,H,C Kavanagh,...,17.2,0.0,0,0,1,1,0,0,46,14

## End of away and home merge + away position

In [46]:
######
###### merging with positions df
#####

In [52]:
final_merged_df = final_merged_df.sort_values(by=['Matchweek', 'season', 'HomeTeam'])
matchweek_positions = matchweek_positions.sort_values(by=['Matchweek', 'season', 'HomeTeam'])

# Remove duplicate columns from final_merged_df if any
final_merged_df = final_merged_df.loc[:, ~final_merged_df.columns.duplicated()]

# Perform the merge on the specified columns
merged_complete = pd.merge(
    final_merged_df,
    matchweek_positions,
    on=['Matchweek', 'season', 'HomeTeam'],
    suffixes=('_home_and_away', '_complete_away_points')  # To handle any potential column name clashes
)

merged_complete

28

## full merge away and home

In [48]:
# Save the DataFrame to a CSV file
merged_complete.to_csv('main_df.csv', index=False)